---
- name: Create K3S config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 644
  with_items:
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s/server/manifests

- name: Provision master nodes
  include_tasks: master.yml
  when: "'master' in group_names"

- name: Provision worker nodes
  include_tasks: worker.yml
  when: "'worker' in group_names"

- name: Set up log rotation
  copy:
    src: files/k3s.logrotate
    dest: /etc/logrotate.d/k3s
