# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine315"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 4096
    v.cpus = 2
    v.linked_clone = true
  end

  config.vm.provider :parallels do |v|
    v.memory = 4096
    v.cpus = 2
    v.linked_clone = true
  end

  # Control Node 1
  config.vm.define "control1" do |control1|
    control1.vm.hostname = "control1"
    control1.vm.network "private_network", ip: "192.168.30.38"
  end

  # Control Node 2
  config.vm.define "control2" do |control2|
      control2.vm.hostname = "control2"
      control2.vm.network "private_network", ip: "192.168.30.39"
  end

  # Control Node 3
  config.vm.define "control3" do |control3|
      control3.vm.hostname = "control3"
      control3.vm.network "private_network", ip: "192.168.30.40"
  end

  # Worker Node 1
  config.vm.define "node1" do |node1|
      node1.vm.hostname = "node1"
      node1.vm.network "private_network", ip: "192.168.30.41"
  end

  # Worker Node 2
  config.vm.define "node2" do |node2|
      node2.vm.hostname = "node2"
      node2.vm.network "private_network", ip: "192.168.30.42"
  end

  config.vm.provision "shell", inline: "apk add python3"

  config.vm.provision "ansible",type: "ansible", run: "never" do |ansible|
    ansible.playbook = "../main.yml"
    ansible.limit = "all"
    ansible.groups = {
      "master" => ["control1", "control2", "control3"],
      "worker" => ["node1", "node2"],
      "k3s_cluster:children" => ["master", "worker"],
      "k3s_cluster:vars" => {
        # "k3s_version" => "latest",
        "k3s_version" => "v1.23.6+k3s1",
        "k3s_token" => "secret-token",
      }
    }
  end

end
