---
- name: k3s.worker | Retrieve token
  set_fact:
    token: "{{ hostvars[groups['master'][0]]['token'] | default(k3s_token) }}"

- name: k3s.worker | Create K3S config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 644
  with_items:
   - /etc/rancher/k3s

- name: k3s.worker | Write K3S env file
  ansible.builtin.template:
    src: templates/k3s.env.j2
    dest: /etc/rancher/k3s/k3s.env
    owner: root
    group: root
    mode: 600

- name: k3s.worker | Create k3s service
  ansible.builtin.copy:
    src: files/k3s.service
    dest: /etc/init.d/k3s
    owner: root
    group: root
    mode: 755

- name: k3s.worker | Start K3S service
  ansible.builtin.service:
    name: k3s
    enabled: yes
    state: started
    runlevel: default
